[project]
name = "avli-workspace"
version = "1.0.0"
description = "Monorepo for agents and ingestor services"
requires-python = ">=3.13"

[dependency-groups]
dev = [
    "prek>=0.4.11,<1.0.0",
    "zizmor>=1.28.0",
]

github-actions = [
    "smokeshow >=0.5.0",
]

[tool.uv.workspace]
members = ["apps/*"]

[tool.typos.files]
extend-exclude = [
    "img/",
    "uv.lock",
    "agents/coverage/",
    "agents/htmlcov/",
]

[tool.typos.default]
extend-ignore-re = [
    # GitHub usernames in @mentions
    "@[a-zA-Z0-9](?:-?[a-zA-Z0-9])*",
    # Name of the package in the PR title
    "Bump certifi ",
]

[tool.typos.default.extend-identifiers]
alls = "alls"
